### ISSUE TITLE
All Tests failing? 

### ISSUE THREAD

**Issue by ghost** [asulwer/tracker-enabled-dbcontext#1]
Hi I'm trying to get the unit tests to run, but no joy, I'm wondering if there is something I'm missing?

Are you doing anything special to get them to run?

Some e.g. errors:
System.Data.SqlClient.SqlException: Invalid object name 'SoftDeletableModels'.
System.Data.SqlClient.SqlException: Invalid object name 'AuditLogs'.

.. Sample stack trace:
Test Name:	CanMigrateOldLogDataToVersion3
Test FullName:	TrackerEnabledDbContext.Core.Tests.MigrationTests.CanMigrateOldLogDataToVersion3
Test Source:	C:\Users\manningd\Downloads\tracker-enabled-dbcontext-master\Tests\TrackerEnabledDbContext.Core.Tests\MigrationTests.cs : line 44
Test Outcome:	Failed
Test Duration:	0:00:00.0318559

Result StackTrace:	
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
--- End of inner exception stack trace ---
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at TrackerEnabledDbContext.Core.TrackerContext.SaveChanges() in C:\Users\manningd\Downloads\tracker-enabled-dbcontext-master\TrackerEnabledDbContext.Core\TrackerContext.cs:line 195
   at TrackerEnabledDbContext.Core.Tests.MigrationTests.InsertFakeLegacyLog() in C:\Users\manningd\Downloads\tracker-enabled-dbcontext-master\Tests\TrackerEnabledDbContext.Core.Tests\MigrationTests.cs:line 201
   at TrackerEnabledDbContext.Core.Tests.MigrationTests.CanMigrateOldLogDataToVersion3() in C:\Users\manningd\Downloads\tracker-enabled-dbcontext-master\Tests\TrackerEnabledDbContext.Core.Tests\MigrationTests.cs:line 51
Result Message:	
Test method TrackerEnabledDbContext.Core.Tests.MigrationTests.CanMigrateOldLogDataToVersion3 threw exception: 
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid object name 'AuditLogs'.

**Comment by ghost** [comment]
It's looking for plural names when the database seems to contain the singular names?

**Comment by ghost** [comment]
The database isn't being initialized!

**Comment by asulwer** [comment]
i am using migrations to initialize the database.  most of the tests are not fully ported over from the EF6 project.
